// Message key externs generated by the Pebble build system.
#pragma once

#include <stdint.h>

extern uint32_t MESSAGE_KEY_COURSE_START;
extern uint32_t MESSAGE_KEY_SERVICE_START;
extern uint32_t MESSAGE_KEY_COURSE_TYPE;
extern uint32_t MESSAGE_KEY_COURSE_ROLE;
extern uint32_t MESSAGE_KEY_ROOM;
extern uint32_t MESSAGE_KEY_PAGODA_CELL;
extern uint32_t MESSAGE_KEY_DINING_HALL;
extern uint32_t MESSAGE_KEY_CUSHION;
extern uint32_t MESSAGE_KEY_REQUEST_SYNC;
